"""HTTP REST client for the Sodex exchange.

Mirrors the Go public SDK's ``client`` package: exposes a single ``Client`` class
that handles signing, nonces, and request/response envelope unwrapping for both
the Spark (spot) and Bolt (perps) engines.
"""

from .client import (
    DEFAULT_BASE_URL,
    DEFAULT_CHAIN_ID,
    DEFAULT_VALUECHAIN_RPC_URL,
    TREASURY_ACCOUNT_ID,
    TESTNET_BASE_URL,
    TESTNET_CHAIN_ID,
    APIError,
    Client,
    Config,
    NotAuthenticatedError,
)
from .types import (
    AccountInfo,
    APIResponse,
    AddAPIKeyRequest,
    Balance,
    Candle,
    CancelOrderResult,
    ChainTransferConfig,
    Coin,
    CoinTransferConfig,
    DepositWithdrawalHistory,
    DepositWithdrawalRecord,
    EVMWithdrawRequest,
    EVMWithdrawSubmission,
    FeeRate,
    FundingPayment,
    GeneratedAPIKey,
    HistoryFilter,
    LeverageResult,
    ModifyOrderResult,
    Order,
    OrderBook,
    OrderBookLevel,
    PlaceOrderResult,
    Position,
    PublicTrade,
    Subaccount,
    Symbol,
    Ticker,
    TransferReceipt,
    UserDepositAddress,
    UserStatus,
    UserSubaccounts,
    UserTrade,
    generate_api_key,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "DEFAULT_CHAIN_ID",
    "DEFAULT_VALUECHAIN_RPC_URL",
    "TREASURY_ACCOUNT_ID",
    "TESTNET_BASE_URL",
    "TESTNET_CHAIN_ID",
    "APIError",
    "APIResponse",
    "AccountInfo",
    "AddAPIKeyRequest",
    "Balance",
    "Candle",
    "CancelOrderResult",
    "ChainTransferConfig",
    "Client",
    "Coin",
    "CoinTransferConfig",
    "Config",
    "DepositWithdrawalHistory",
    "DepositWithdrawalRecord",
    "EVMWithdrawRequest",
    "EVMWithdrawSubmission",
    "FeeRate",
    "FundingPayment",
    "GeneratedAPIKey",
    "HistoryFilter",
    "LeverageResult",
    "ModifyOrderResult",
    "NotAuthenticatedError",
    "Order",
    "OrderBook",
    "OrderBookLevel",
    "PlaceOrderResult",
    "Position",
    "PublicTrade",
    "Subaccount",
    "Symbol",
    "Ticker",
    "TransferReceipt",
    "UserDepositAddress",
    "UserStatus",
    "UserSubaccounts",
    "UserTrade",
    "generate_api_key",
]
