"""WebSocket client for the Sodex real-time API.

Mirrors the Go public SDK's ``ws`` package.
"""

from .client import AccountSubscription, Client
from .types import (
    CHANNEL_ACCOUNT_EVENT,
    CHANNEL_ACCOUNT_ORDER_UPDATE,
    CHANNEL_ACCOUNT_STATE,
    CHANNEL_ACCOUNT_TRADE,
    CHANNEL_ACCOUNT_UPDATE,
    CHANNEL_ALL_BOOK_TICKER,
    CHANNEL_ALL_MARK_PRICE,
    CHANNEL_ALL_MINI_TICKER,
    CHANNEL_ALL_TICKER,
    CHANNEL_BOOK_TICKER,
    CHANNEL_CANDLE,
    CHANNEL_L2_BOOK,
    CHANNEL_L4_BOOK,
    CHANNEL_MARK_PRICE,
    CHANNEL_MINI_TICKER,
    CHANNEL_TICKER,
    CHANNEL_TRADE,
    AccountOrderUpdate,
    AccountTrade,
    BookTicker,
    Candle,
    L2Book,
    MarkPrice,
    MiniTicker,
    Push,
    SubscribeParams,
    Ticker,
    Trade,
)

__all__ = [
    "AccountOrderUpdate",
    "AccountSubscription",
    "AccountTrade",
    "BookTicker",
    "CHANNEL_ACCOUNT_EVENT",
    "CHANNEL_ACCOUNT_ORDER_UPDATE",
    "CHANNEL_ACCOUNT_STATE",
    "CHANNEL_ACCOUNT_TRADE",
    "CHANNEL_ACCOUNT_UPDATE",
    "CHANNEL_ALL_BOOK_TICKER",
    "CHANNEL_ALL_MARK_PRICE",
    "CHANNEL_ALL_MINI_TICKER",
    "CHANNEL_ALL_TICKER",
    "CHANNEL_BOOK_TICKER",
    "CHANNEL_CANDLE",
    "CHANNEL_L2_BOOK",
    "CHANNEL_L4_BOOK",
    "CHANNEL_MARK_PRICE",
    "CHANNEL_MINI_TICKER",
    "CHANNEL_TICKER",
    "CHANNEL_TRADE",
    "Candle",
    "Client",
    "L2Book",
    "MarkPrice",
    "MiniTicker",
    "Push",
    "SubscribeParams",
    "Ticker",
    "Trade",
]
